### ISSUE TITLE
Reasoning behind associated `Size` / `Units` types on various traits?

### ISSUE THREAD

**Issue by luser** [m4b/scroll#37]
I've stumbled over this before while writing functions that were generic over `TryIntoCtx` and `SizeWith`--the constraints need to explicitly call out `TryIntoCtx<Size=usize>` or `SizeWith<Units=usize>` in order to be able to actually *use* the sizes for anything meaningful.

Both `MeasureWith` and `SizeWith` have an associated `Units` type:
https://docs.rs/scroll/0.9.0/scroll/ctx/trait.MeasureWith.html#associatedtype.Units
https://docs.rs/scroll/0.9.0/scroll/ctx/trait.SizeWith.html#associatedtype.Units

And both `TryFromCtx` and `TryIntoCtx` have an associated `Size` type:
https://docs.rs/scroll/0.9.0/scroll/ctx/trait.TryFromCtx.html#associatedtype.Size
https://docs.rs/scroll/0.9.0/scroll/ctx/trait.TryIntoCtx.html#associatedtype.Size

I'm sure you had an intended use case for this being generic when you wrote these, but is it actually something that has proven useful in practice? grepping through the `scroll`, `scroll_derive` and `goblin` repositories shows that there aren't any implementations of these traits using anything but `usize`, and most usage in `goblin` is via the derives, which all provide implementations where the types are `usize`.

I know it would be a breaking change, but removing these associated types and just using `usize` everywhere seems like it would simplify things a bit.

The only counter-argument I can come up with on my own is that perhaps you might want to have types that have sizes that don't fit in 32 bits but you want to use them with these traits in 32-bit code, but this feels a bit contrived and also would suggest that just using `u64` instead of `usize` everywhere would be the answer.

**Comment by m4b** [comment]
Will write thoughts more on weekend but briefly:

1. I’m open to removing it
2. It will probably be a lot of work

Original usecase of generic index was that you might want to use some other mechanism to index into something other than bytes (think Index trait); however in practice implementing this in scroll itself never materialized (non generic bytes itself were used as the final indexee in the various Try* traits).

As for SizeWith I can’t remember why I added that associated type ? I probably had generic fever ? Was worried about something ? Added it because I couldn’t get the Pread traits to compile ?

Is MeasureWith used anywhere ? That might be accidentally included from old prototypes or maybe it’s used.

My experience with scroll hyper genetics is that I don’t like to mess with them anymore because it’s a compilation nightmare to change things and have all the tests pass and etc.  Half of the tests are just to ensure client can actually use the trait as intended.

Anyway yea I’m up for simplifying and cleaning up the interface before a final 1.0 release but I think it will definitely be some work...

**Comment by luser** [comment]
It's certainly not critical, it's just one of those things I trip over when writing code that's generic over the `scroll` traits.

**Comment by m4b** [comment]
Well I think its important to get right; if it's annoying to use/remember and doesn't add any benefit (and never will in the foreseeable future), then I think its ok to break before 1.0.

I don't think I have much else to say actually than what I wrote above; I personally don't have time for refactoring scroll at the moment to do this change, but I'd cautiously be optimistic about any PR/changes which would, given list of things being changed, rationale, etc.

**Comment by willglynn** [comment]
These got changed to `usize` in #45.
