### ISSUE TITLE
What does the "g" in "gread" stand for?

### ISSUE THREAD

**Issue by whatisaphone** [m4b/scroll#60]
Fun fact: the docs for the `gread` method do not even contain the letter "g" :)

>Reads a value from self at offset with a default Ctx. For the primitive numeric values, this will read at the machine's endianness. Updates the offset

I was able to figure out the meaning of `cread` and `pread`, but `gread` escapes me. What does the "g" stand for?

**Comment by m4b** [comment]
@whatisaphone So glad you asked ! :D so the lore of scrolls name is that there were originally the lesser and greater scrolls, which were used to scroll through buffers, hence the crate name.

The lesser scroll was effectively pread (named lread), and the greater scroll was gread, hence the g. The greater scroll was a more powerful source of byte reading magic because it updated the offset for you, instead of the lowly lread which did not.

The greater scroll also built upon the lesser scroll trait, hence it was also greater.

Over time they inherited the names they have now, because like all magical things, they were too esoteric and added more confusion than helped.

And that’s the whole story :)

I suppose before 1.0 perhaps gread could be renamed ? This will be difficult, because unfortunately over time I’ve became fond of it, although I could be convinced.

Do you have any suggestions for a different name ? :)

**Comment by whatisaphone** [comment]
Interesting, now I know! I'm glad you're making parsing magic more accessible to puny mortals like myself.

So how did `Cread`, the least out of all the scrolls, end up in `greater.rs`? :)

>Do you have any suggestions for a different name ? :)

If it were my library, I think `gread` would be called `cread`, for ***c***ursor, but that's already taken. (Though maybe it doesn't need to be, since there shouldn't be anything stopping `Pread` from also working on `core`-only.) My second choice would be `mread`, for ***m***utating the offset. But it's your lib, not mine, and I only came here to ask a question, not rename all your methods!

A tangent about `cread`—I think it might be a good idea for this lib to describe itself as a cursor library, or at least describe `Pread` as a cursor trait. It basically boils down to a `std::io::Cursor`, except the data and offset are stored separately, so one of them can be mutable while the other is immutable, making zero-copy reads possible (unlike a `Cursor`). If I had read the word "cursor", I think I would have gotten the point of the lib a lot quicker.

But hey, I'm just this guy, and that's just my opinion. Thanks for a useful lib!

**Comment by m4b** [comment]
No this is great feedback! Don’t be afraid to share opinions (here at least) :) let me know if you have any other questions
