### ISSUE TITLE
Publish new versions to crates.io

### ISSUE THREAD

**Issue by atouchet** [m4b/scroll#63]
The latest versions on crates.io are scroll 0.9.2 and scroll_derive 0.9.5 while on GitHub they are on 0.10.0 and 0.10.1.

**Comment by m4b** [comment]
Yes we need to publish; I can do tonight. I was hoping to land some more breaking changes in 0.10 but I think we need a super hero to come and push it through 😃

**Comment by jacobrosenthal** [comment]
ping ;) I love the library, I built something against head so Im waiting for the 0.10 release too

**Comment by m4b** [comment]
Hi everyone serious apologies for delay, I totally spaced on this :( should be latest version on crates.io now 0.10;

For the future me/whoever, I had to comment the scroll-derive dev dependency on scroll, since it requires 0.10, but that's not published, and it can't be published until scroll-derive is published (since it depends on it), so to break the circular dep i have to publish scroll-derive without the dev-dep, then `git stash pop`.

Anyway, this should be good now, enjoy, and sorry for delay ! :)

**Comment by m4b** [comment]
Just FYI, version `0.10.0` was yanked; it didn't pub use the derive stuff, so it broke downstream crates who used the `features = ["derive"]`; this is fixed in new published version of `0.10.1`, sorry for any invonvenience
