### ISSUE TITLE
the trait bound `usize: FromCtx<_>` is not satisfied when testing with derive

### ISSUE THREAD

**Issue by nyurik** [m4b/scroll#85]
This fails:

```
> cargo test --all-features


failures:

---- src/lib.rs - readme_tests (line 391) stdout ----
error[E0277]: the trait bound `usize: FromCtx<_>` is not satisfied
  --> src/lib.rs:401:30
   |
12 |     let foo = bytes.ioread::<usize>()?;
   |                              ^^^^^ the trait `FromCtx<_>` is not implemented for `usize`
   |

... 
```

**Comment by m4b** [comment]
Yea not reading out `usize` is intentional (I.e., FromCtx not implemented); in the past we had this, in 0.10, i believe, but I removed it because it's not really a good idea; usize can be 32/64 bits depending on the platform, which means the wire size you read out changes depending on what kind of machine you're on. This is not really a usecase I want to support in scroll, and in general it's bad practice (the size of something you read out of bytes depends on which machine you're on?)
